version: "3.7"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - "./src:/app/src"
      - "./alembic:/app/alembic"
    env_file:
      - ./src/.env.dev
    entrypoint: ["sh", "./entrypoint.sh"]
    depends_on:
      - db
  db:
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/.env.dev

volumes:
  postgres_data:
